import React from 'react';
import Head from 'next/head';
// import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Corpobello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/3Ryht66/Corpobello-Logo-Corto.png" />
      </Head>
      <main>
        <h1>Estas en home</h1>
      </main>
    </>
  );
}
