export default {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  ERROR_GENERIC: 'ERROR_GENERIC',
  LOAD_RESERVES: 'LOAD_RESERVES',
  CREATE_RESERVES: 'CREATE_RESERVES',
};
